services:
  api:
    container_name: evolution_api
    build:
      context: .
    image: evolution-api:local
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
      - supabase_default
    env_file:
      - .env
    expose:
      - "8080"

  frontend:
    container_name: evolution_frontend
    image: evoapicloud/evolution-manager:latest
    restart: always
    ports:
      - "3000:80"
    networks:
      - evolution-net
      - supabase_default
    volumes:
      - ./Docker/nginx-manager.conf:/etc/nginx/conf.d/nginx.conf:ro

volumes:
  evolution_instances:

networks:
  evolution-net:
    name: evolution-net
    external: true
  supabase_default:
    external: true
